import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import BLOG from "../../blog.config";
import "./globals.css";
import Header from "@/components/Header";
import cn from "classnames";
import Footer from "@/components/Footer";
import loadLocale from "../../assets/i18n";
import { ConfigProvider } from "@/lib/config";
import { LocaleProvider } from "@/lib/locale";
import { ThemeProvider } from "@/lib/theme";
import blogConfig from "../../blog.config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await loadLocale("basic", "en-US");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className={`wrapper ${
            BLOG.font === "serif" ? "font-serif" : "font-sans"
          }`}
        >
          <ConfigProvider value={blogConfig}>
            <LocaleProvider value={locale}>
              <ThemeProvider>
                <Header />
                <main
                  className={cn("flex-grow transition-all", [
                    "self-center px-4",
                    "w-full max-w-2xl",
                  ])}
                >
                  {children}
                </main>
                <Footer />
              </ThemeProvider>
            </LocaleProvider>
          </ConfigProvider>
        </div>
      </body>
    </html>
  );
}
